<a href="https://colab.research.google.com/github/sathundorn/Statistical-Learning-Labs1/blob/main/Copy_of_Lab08_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [1]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [2]:
a = torch.tensor([1.])
a

tensor([1.])

### Convert a tensor to scalar

In [3]:
b = a[0].item()
b

1.0

### Creating 2D tensor

In [4]:
c = torch.tensor([[1., 2.], [3., 4.]])
c

tensor([[1., 2.],
        [3., 4.]])

## Tensor and Numpy

### Convert from tensor to numpy array

In [5]:
d = c.numpy()
d

array([[1., 2.],
       [3., 4.]], dtype=float32)

### Convert from numpy array to tensor

In [6]:
f = torch.from_numpy(d)
f

tensor([[1., 2.],
        [3., 4.]])

## PyTorch and GPU

check if GPU is available

In [7]:
torch.cuda.is_available()

True

In [8]:
c = c.cuda()
c

tensor([[1., 2.],
        [3., 4.]], device='cuda:0')

In [9]:
e = c.cpu().numpy()
e

array([[1., 2.],
       [3., 4.]], dtype=float32)

## Basic operations

In [10]:
c * 2

tensor([[2., 4.],
        [6., 8.]], device='cuda:0')

In [12]:
c - 1

tensor([[0., 1.],
        [2., 3.]], device='cuda:0')

### Matrix multiplication

In [13]:
A = torch.tensor([[4, 5], [8, 9]])
B = torch.tensor([[1, 4], [7, 8]])

torch.matmul(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [14]:
torch.mm(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [15]:
A @ B

tensor([[ 39,  56],
        [ 71, 104]])

### Matrix transpose

In [16]:
A.t()

tensor([[4, 8],
        [5, 9]])

## Creating a specific type of tensor

In [17]:
a = torch.zeros(1, 2, 3)
a

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [18]:
b = torch.ones(1, 2, 3)
b

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [19]:
I = torch.eye(3)
I

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [20]:
R1 = torch.rand(2, 3)
R1

tensor([[0.1136, 0.1214, 0.6290],
        [0.9542, 0.4416, 0.2545]])

In [21]:
R2 = torch.randn(2, 3)
R2

tensor([[-0.2426,  0.6993,  0.5992],
        [ 1.0810,  1.1849, -0.0122]])

In [22]:
a = torch.arange(6)
a

tensor([0, 1, 2, 3, 4, 5])

## Tensor's shape

In [24]:
R1.shape

torch.Size([2, 3])

### Checking the shape of a tensor

In [25]:
u = torch.arange(6)
u.shape

torch.Size([6])

### Changing the shape of a tensor

In [26]:
v = u.reshape(2, 3)
v.shape

torch.Size([2, 3])

In [27]:
w = u.view(3, 2)
w

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [28]:
a = torch.arange(4)
b = torch.arange(4) + 1

c = torch.stack([a, b], axis=0)
c

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4]])

In [29]:
d = torch.stack([a, b], axis=1)
d

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])

In [30]:
# concatenate
e = torch.cat([a, b], axis=0)
e

tensor([0, 1, 2, 3, 1, 2, 3, 4])

In [31]:
display(a,b)

tensor([0, 1, 2, 3])

tensor([1, 2, 3, 4])

In [32]:
f = torch.cat([a.reshape(2, 2), b.reshape(2, 2)], axis=0)
f

tensor([[0, 1],
        [2, 3],
        [1, 2],
        [3, 4]])

### Squeezing a tensor (removing an extra dimension)

In [33]:
A = torch.zeros(1, 2, 3)
B = A.squeeze()
B

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [34]:
C = B.unsqueeze(axis=0)
C

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

### Unsqueezing a tensor (adding an extra dimension)

In [ ]:
# H.shape = (6, )


## Indexing

In [35]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


In [36]:
torch.inverse(torch.tensor([[1., 2.], [3., 4.]]))

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [45]:
# X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
# print(X)

# X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
# print(X)

In [47]:
X = torch.randn(200, 7)
b = torch.randn(8, 1)
e = torch.randn(200, 1)

In [48]:
ones_column = torch.ones(200, 1)

In [49]:
X = torch.cat([ones_column, X], axis=1)
X

tensor([[ 1.0000,  0.3734,  0.3453,  ..., -1.2711,  0.9560,  0.7269],
        [ 1.0000, -0.0104, -0.9733,  ...,  0.6809, -0.3904, -1.0541],
        [ 1.0000,  0.6185,  0.2836,  ...,  0.3682,  0.2630,  0.7846],
        ...,
        [ 1.0000, -0.1277, -0.2267,  ..., -0.7811, -0.4243,  0.6273],
        [ 1.0000, -0.6910,  0.7430,  ...,  0.8784,  2.1306, -1.8060],
        [ 1.0000, -1.5665,  0.6784,  ..., -1.5721, -0.4832, -0.4754]])

In [ ]:
y = X @ b + e
y

In [51]:
b_hat = torch.inverse(X.t() @ X) @ X.t() @ y
b_hat

tensor([[-0.6407],
        [-1.9317],
        [ 1.6165],
        [ 0.5255],
        [-0.5440],
        [ 0.2979],
        [-0.6651],
        [-0.4054]])

In [ ]:
y_hat = X @ b_hat
y_hat

In [53]:
y = y.numpy()
y_hat = y_hat.numpy()

In [54]:
MSE = (1/200) * (np.sum((y - y_hat)**2))
MSE

np.float32(0.861214)